### PR TITLE
Added support for file / thumbnail during triplestore injest

### PR DESCRIPTION
**Pull request by justgo129**

### CODE REVIEW

**Comment by justgo129** [comment]
@rewolfe since http://data.globalchange.gov/file returns a 404 but all "files" have a URI with the format http://data.globalchange.gov/file/foo , are additional changes needed to facilitate ingest?  Is there a way to test the ingest?

**Comment by lomky** [comment]
Requires a test pass on dev before merge.

**Comment by lomky** [comment]
@justgo says the URIs for files differ, and we may wish to make the URI  similar to those for figures (i.e. URI tied to a specific publication even though data.globalchange.gov/figure resolves).

**Comment by rewolfe** [comment]
@lomky - This doesn't work yet.   We need to implement the API call for "/file", like "/figure" that will produce the TTL that can then be used to load the RDF.  Another ticket on USGCRP/gcis should be created and linked to this one (as a precursor).

**Pull request closed without merging**
